version: '3.8'


services:
    app_ts:
        build:
            context: . 

        environment:
            - SECRET_KEY=samplesecretkey123 
            - ALLOWED_HOSTS=127.0.0.1, localhost
    
    proxy:
        build: 
            context: ./proxy
        ports:
            - "8000:8000"
        depends_on:
            - app_ts
        