version: '3.8'

services:
  atus:
    build: . 
    command: >
      sh -c " python manage.py runserver 0.0.0.0:8000 "
    environment:
        - DEBUG=1
    depends_on:
      atus-db

     
    volumes:
      - ./:/code
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
    - atus-db
  atus-db:
      image: postgres:13
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_USER=atus
        - POSTGRES_PASSWORD=88658710
        - POSTGRES_DB=atus_dev
  
volumes:
    postgres_data: